### ISSUE TITLE
jqplot to image: legend swatches overlapping in jQuery > 3.2.1

### ISSUE THREAD

**Issue by SunflowerFuchs** [jqPlot/jqPlot#186]
In jQuery up to 3.2.1, when asking for the `position()` of a `div` in a `td`, the position would be relative to the table. Since 3.3.0+, the position is relative to the `td`, so that all swatches have a position of 0/0 and lay over each other.

jQuery 3.2.1:
![image](https://user-images.githubusercontent.com/18332886/57602714-351e5000-7560-11e9-93f9-2005453dbffd.png)

jQuery 3.3.1:
![image](https://user-images.githubusercontent.com/18332886/57602677-1cae3580-7560-11e9-93e9-237625c3aff2.png)

**Comment by FacilitorKoen** [comment]
Experiencing the same issue.
Legend-labels, when centered, also seem affected (unsure if this is the same problem)

**Comment by robertoferreirajrr** [comment]
![chart17cm (39)](https://user-images.githubusercontent.com/264819/79127069-8ee25800-7d77-11ea-974b-90fa737c2ef6.png)

I have implemented a fix in function _jqpToImage, works for me:

```
$(el).find('div.jqplot-table-legend-swatch-outline').each(function () {
     // get the first div and stroke it
     var elem = $(this);
     newContext.strokeStyle = elem.css('border-top-color');

     newContext.strokeStyle = elem.css('border-top-color');


    var containerOffset = elem.parent().parent().offset();

    var rowOffset = elem.offset();
    console.log(containerOffset.top);

    var position = {
               top: ((rowOffset.top - containerOffset.top) * 5) == 0 ? 3 : (rowOffset.top - containerOffset.top) * 5,
               left: rowOffset.left - containerOffset.left
                              };
    console.log(position);

    var l = left + position.left;
    var t = top + position.top;
    //newContext.strokeRect(l, t, elem.innerWidth(), elem.innerHeight());

    // now fill the swatch

    l += parseInt(elem.css('padding-left'), 10);
    t += parseInt(elem.css('padding-top'), 10);
    var h = elem.innerHeight() - 2 * parseInt(elem.css('padding-top'), 10);
    var w = elem.innerWidth() - 2 * parseInt(elem.css('padding-left'), 10);


    var swatch = elem.children('div.jqplot-table-legend-swatch');
    newContext.fillStyle = swatch.css('background-color');
    newContext.fillRect(l, t, w, h);
    console.log(t);
});
```

**Comment by GitHubUser4234** [comment]
Hi @robertoferreirajrr,  I have tried your fix for pie charts (jqplot.1.0.9.d96a669 / jquery 3.6.0), but unfortunately it doesn't really fix the issue in this case. However a slight change in the legend swatches can be noticed:

**Without the fix**:
![image](https://user-images.githubusercontent.com/16538178/144978883-a83e5ce5-980b-4aea-9085-ffcc141f6fc6.png)

**With the fix:**
![image](https://user-images.githubusercontent.com/16538178/144978964-f6da4769-a643-424a-a7b5-ec0852bccf63.png)

**Comment by GitHubUser4234** [comment]
With the following code it looks quite right:

                // find all the swatches
                $(el).find('div.jqplot-table-legend-swatch-outline').each(function() {
                    // get the first div and stroke it
                    var elem = $(this);
                    newContext.strokeStyle = elem.css('border-top-color');
					
					var elOffset = $(el).offset();
					
					var rowOffset = elem.parent().offset();
					
					var customPosition = {
						top: rowOffset.top - elOffset.top + parseInt(elem.parent().css('padding-top'), 0),
						left: rowOffset.left - elOffset.left + parseInt(elem.parent().css('padding-left'), 0)
					};
					
                    var l = left + customPosition.left;
                    var t = top + customPosition.top;
                    newContext.strokeRect(l, t, elem.innerWidth(), elem.innerHeight());

                    // now fill the swatch
                    
                    l += parseInt(elem.css('padding-left'), 10);
                    t += parseInt(elem.css('padding-top'), 10);
                    var h = elem.innerHeight() - 2 * parseInt(elem.css('padding-top'), 10);
                    var w = elem.innerWidth() - 2 * parseInt(elem.css('padding-left'), 10);

                    var swatch = elem.children('div.jqplot-table-legend-swatch');
                    newContext.fillStyle = swatch.css('background-color');
                    newContext.fillRect(l, t, w, h);
                });

**Result:**
![image](https://user-images.githubusercontent.com/16538178/145050479-745c1e39-1d7f-49ca-819a-42b333f8acb9.png)
